spring.application.name=mapu-market
server.port=8090
server.servlet.context-path=/mapu-market
#Database
spring.datasource.url=jdbc:postgresql://localhost:5432/mapu_market
spring.datasource.username=postgres
spring.datasource.password=nala
spring.datasource.driver-class-name=org.postgresql.Driver
